In [1]:
from sklearn.datasets import load_diabetes

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import time

In [2]:
x,y = load_diabetes(return_X_y=True)

In [3]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [4]:
reg = LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [5]:
reg.coef_ 

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [6]:
reg.intercept_

151.88331005254167

In [7]:
y_pred = reg.predict(x_test)
r2_score(y_test,y_pred)

0.4399338661568968

In [16]:
import random

class MBGDRegressor:
    
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        
    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            
            for j in range(int(X_train.shape[0]/self.batch_size)):
                
                idx = random.sample(range(X_train.shape[0]),self.batch_size)
                
                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                #print("Shape of y_hat",y_hat.shape)
                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)

                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [17]:
batch_size = int(x_train.shape[0]/10)             ### 35
mbr = MBGDRegressor(batch_size=batch_size,learning_rate=0.01,epochs=50)

In [18]:
mbr.fit(x_train,y_train)

152.86149015980178 [  61.74249311  -65.56870082  335.73741791  247.89143902   20.73799757
  -25.93200666 -178.32413838  135.63285192  326.95438206  126.13076512]


In [19]:
y_pred = mbr.predict(x_test)
r2_score(y_test,y_pred)

0.4305027284391948

# Using SKlearn

In [20]:
from sklearn.linear_model import SGDRegressor

In [21]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.2)

In [29]:
batch_size = 35

for i in range(100):
    
    idx = random.sample(range(x_train.shape[0]),batch_size)
    sgd.partial_fit(x_train[idx],y_train[idx])

In [30]:
sgd.coef_

array([  36.20451258, -120.45467611,  426.5632456 ,  326.14061899,
        -11.23164374,  -68.98611268, -183.10651251,  119.46893791,
        395.19372911,  117.36987233])

In [31]:
sgd.intercept_

array([135.76141644])

In [32]:
y_pred = sgd.predict(x_test)
r2_score(y_test,y_pred)

0.3967670576009975