In [9]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.datasets import make_classification
from sklearn.inspection import permutation_importance as pi

In [5]:
x,y = make_classification(n_samples=5,n_classes=2,n_informative=2,n_redundant=0,random_state=0,n_features=2)

In [6]:
lor = LogisticRegression()
dt = DecisionTreeClassifier()
rf = RandomForestClassifier()
knn = KNeighborsClassifier()

In [7]:
lor.fit(x,y)
dt.fit(x,y)
rf.fit(x,y)
knn.fit(x,y)

KNeighborsClassifier()

### Permutation importance

In [10]:
print('feature importance for lor : ',pi(lor,x,y,n_repeats=5))

feature importance for lor :  {'importances_mean': array([0.  , 0.32]), 'importances_std': array([0.  , 0.16]), 'importances': array([[0. , 0. , 0. , 0. , 0. ],
       [0. , 0.4, 0.4, 0.4, 0.4]])}


In [11]:
print('feature importance for dt : ',pi(dt,x,y,n_repeats=5))

feature importance for dt :  {'importances_mean': array([0.32, 0.24]), 'importances_std': array([0.09797959, 0.1496663 ]), 'importances': array([[0.4, 0.2, 0.2, 0.4, 0.4],
       [0.2, 0.4, 0.4, 0.2, 0. ]])}


In [12]:
print('feature importance for knn : ',pi(knn,x,y,n_repeats=5))

feature importance for knn :  {'importances_mean': array([0., 0.]), 'importances_std': array([0., 0.]), 'importances': array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])}


In [13]:
print('feature importance for rf : ',pi(rf,x,y,n_repeats=5))

feature importance for rf :  {'importances_mean': array([0.28, 0.24]), 'importances_std': array([0.09797959, 0.1496663 ]), 'importances': array([[0.2, 0.2, 0.4, 0.4, 0.2],
       [0.4, 0. , 0.4, 0.2, 0.2]])}


In [14]:
result = pi(lor,x,y)

In [15]:
result.importances

array([[0. , 0. , 0. , 0. , 0. ],
       [0.4, 0.4, 0.4, 0.4, 0.4]])

In [16]:
result.importances_mean

array([0. , 0.4])

In [17]:
result.importances_std

array([0., 0.])